org: doctorew
app: minimester-graphql
service: minimester-graph-lambda

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev # default stage

functions:
  pocketMorty:
    handler: dist/server-lambda.handler
    events:
      - http:
          path: rickmorty
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
  chat:
    handler: dist/server-lambda.handler
    events:
      - http:
          path: api/chat
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-plugin-include-dependencies

custom:
  serverless-offline:
    httpPort: 4000
  customDomain:
    domainName: mms-graph.doctorew.com
    stage: ${self:provider.stage}
    basePath: ''
    certificateName: '*.doctorew.com'
    createRoute53Record: true
    endpointType: 'edge'
    securityPolicy: tls_1_2
  includeDependencies:
    enableCaching: true
